apiVersion: v1
kind: ConfigMap
metadata:
  name: {{PIPELINE_ENGINE_NAME}}-configmap
  namespace: {{KUBERNETES_NAMESPACE}}
data:
  TZ: "America/Los_Angeles"
  PIPELINE_ENGINE_NAME: {{PIPELINE_ENGINE_NAME}}
  KUBERNETES_CLUSTER: {{KUBERNETES_CLUSTER}}
  KUBERNETES_NAMESPACE: {{KUBERNETES_NAMESPACE}}
  KUBERNETES_APISERVER_URL: {{KUBERNETES_APISERVER_URL}}
  KUBERNETES_SERVICE_ACCOUNT_NAME: {{KUBERNETES_SERVICE_ACCOUNT_NAME}}
  CASC_JENKINS_CONFIG: "/var/jenkins_home/casc_configs"
  CASC_JENKINS_CONFIG_REPO: {{CASC_JENKINS_CONFIG_REPO}}
  CASC_JENKINS_CONFIG_REPO_USERNAME: {{CASC_JENKINS_CONFIG_REPO_USERNAME}}
  CASC_JENKINS_CONFIG_PROFILE: "jcasc.yml"
  MASTER_CPU: "2000"
  MASTER_MEMORY: "8192"
  MASTER_DOCKER_IMAGE: {{MASTER_DOCKER_IMAGE}}
  AGENT_CPU: "1000"
  AGENT_MEMORY: "4096"
  AGENT_PORT: "50000"
  AGENT_EXECUTORS: "100"
  AGENT_DOCKER_IMAGE: {{AGENT_DOCKER_IMAGE}}
  HEALTH_URI: "/login"
  HEALTH_STATUS_CODE: "200"
  SERVER_PORT: "8080"
  JENKINS_ADMIN_ADDRESS: "{{PIPELINE_ENGINE_NAME}}@localhost"
  JENKINS_URL: {{JENKINS_URL}}
  PIPELINE_INGRESS_URL: {{PIPELINE_INGRESS_URL}}
  PIPELINE_INTERNAL_TEMPLATES_REPO: {{PIPELINE_INTERNAL_TEMPLATES_REPO}}
  PIPELINE_INTERNAL_TEMPLATES_JENKINS_CREDENTIAL_ID : {{PIPELINE_INTERNAL_TEMPLATES_JENKINS_CREDENTIAL_ID}}
  PIPELINE_GLOBAL_LIBRARY_URL: "https://github.com/tmobile/POET-pipeline-library.git"
  CASC_JENKINS_CONFIG_REPO_PASSWORD: {{BASE64_ENC_CASC_JENKINS_CONFIG_REPO_PASSWORD}} 
  PIPELINE_ENGINE_BACKUP_REPO_PASSWORD: {{BASE64_ENC_PIPELINE_ENGINE_BACKUP_REPO_PASSWORD}}
  BACKUP_PIPELINE_ENGINE: "false"
  RESTORE_PIPELINE_ENGINE: "false"
  PIPELINE_ENGINE_BACKUP_SERVER_URL: {{PIPELINE_ENGINE_BACKUP_SERVER_URL}}
  PIPELINE_ENGINE_BACKUP_PROJECT: {{PIPELINE_ENGINE_BACKUP_PROJECT}}
  PIPELINE_ENGINE_BACKUP_REPO: {{PIPELINE_ENGINE_BACKUP_REPO}}
  PIPELINE_ENGINE_BACKUP_REPO_USERNAME: {{PIPELINE_ENGINE_BACKUP_REPO_USERNAME}}
  GIT_USER_NAME: {{GIT_USER_NAME}}
  GIT_USER_EMAIL: {{GIT_USER_EMAIL}}
