apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: {{PIPELINE_ENGINE_NAME}}
  name: {{PIPELINE_ENGINE_NAME}}-service
  namespace: {{KUBERNETES_NAMESPACE}}
spec:
  ports:
    - name: master
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: agent
      protocol: TCP
      port: 50000
      targetPort: 50000
  selector:
    k8s-app: {{PIPELINE_ENGINE_NAME}}
  sessionAffinity: ClientIP
  type: ClusterIP
